### ISSUE TITLE
Creating mulitple volumes sometimes fails

### ISSUE THREAD

**Issue by decentral1se** [ansible-community/molecule-hetznercloud#25]
When I do the following:

```yaml
volumes:
  - name: "molecule-hetznercloud-volume-1-${INSTANCE_UUID}"
  - name: "molecule-hetznercloud-volume-2-${INSTANCE_UUID}"
```

It sometimes fails with some sort of JSON related error which I don't have right now. It is flaky.

This could be the underlying library or the play implementation. Unsure.

/cc @xoxys
