### ISSUE TITLE
VM name prefix not matching inventory_hostname causes vars not to be loaded

### ISSUE THREAD

**Issue by tumbl3w33d** [ansible-community/molecule-hetznercloud#89]
Hello,

TL;DR:

- molecule knows instances by their name defined in the `platforms` section
- `molecule-hetznercloud` prefixes instances (by default a dynamic string, computed by md5 of the scenario path)
- if you use an additional inventory that works with the hcloud API, you must be aware the instances names in hcloud won't match the host names in your play, i.e. host_vars also won't match
- my workaround is to define a static prefix (`RESOURCE_NAMESPACE`) and remove that prefix on-the-fly from the instance names in my dynamic inventory

**Long story:**

I define my instances in the `platforms` attribute like this:
```yaml
platforms:
  - name: "${$USER}-app-01"
    groups:
      - my_servers
 […]
  ```
and in my `converge.yml` I target the hosts like
```yaml
- name: Converge
  hosts: my_servers
```
This basically works. However, I also link my dynamic inventory
```yaml
provisioner:
[…]
  inventory:
    links:
      hosts: "../../../../inventories/hcloud_inventory.py"
```
which picks up my hosts and sets some hostvars each. Now the problem is, my tests run against the group's hosts like `tumble-app-01`, but in the background the hcloud driver prefixes VMs with a resource namespace (with fallback to a md5 of the scenario path which effectively is the value, because I didn't set that env myself).

The result is that my dynamic inventory knows a host like `<md5>-tumble-app-01` which is not the same as the one used in the molecule run (`tumble-app-01`) which in turn means that my hostvars are not loaded.

I added a workaround to my dynamic inventory to remove that prefix from the host, when a certain env var is set:

```python
    # for molecule-based tests running in hcloud
    if "VM_PREFIX_TO_REMOVE" in os.environ:
        vm_name = vm_name.replace(os.environ["VM_PREFIX_TO_REMOVE"], "", 1)
 ```
 That's not pretty, but I could live with it. However, I struggle to dynamically set that env for the run:
 
 ```yaml
provisioner:
[…]
  env:
    ANSIBLE_ROLES_PATH: "../../../../roles:../../../../common-roles"
    INV_HCLOUD_TOKEN: "${HCLOUD_TOKEN}"
    #VM_PREFIX_TO_REMOVE: "{{ '${MOLECULE_SCENARIO_DIRECTORY}' | md5 }}-" # this does not work, no interpolation
    VM_PREFIX_TO_REMOVE: 19fa9d8fc0b584b2b5e2704a69929e2d-
```
The statically set prefix leads to my inv removing that part of the host name and my play picks up the vars as expected. What I can do is setting `RESOURCE_NAMESPACE` there, so I know the static string that I need to remove from the host names.

It's all a little awkward. I guess there's no way for you to influence the host names molecule works with. I tried targeting the hosts directly instead of the group like
```yaml
  hosts:
    - "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') | md5 }}-app-01"
    - "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') | md5 }}-app-02"
```
and that basically works, however, it's somehow out of sync with the molecule universe so it doesn't know how to reach these hosts and the play fails with unreachable (permission denied).

I guess I will continue with the static prefix for now as that does the trick for me due to the workaround in my inventory. Feel free to close the issue if you think that's the best we can do.
